/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        if (n <= 1) {
            return false;
        }
        if (n == 2) {
            return true;
        }
        for (long i = 2; i <= (long)Math.sqrt(n); i++) {
            if (n%i == 0) {
                return false;
            }
        }
        return true;
    }   
    public long firstPrimeNumberIn(String n) {
        for (int i = 0; i < n.length(); i++) {
            long value = Long.parseLong(n.substring(i, i + 10));
            if (isPrime(value)) {
                return value;
            }
        }
        return -1;
    }
}
